### ISSUE TITLE
Does xmppjs support xmpp dataforms(XEP-0004: Data Forms)

### ISSUE THREAD

**Issue by gurukini** [mwild1/xmppjs#4]
Hi,

I am very much new to xmpp.js. Before i want to start working on xmpp.js I wanted to know below given two requirements.
a) BOSH support
b) Data Forms support

I found "node-xmpp-bosh" which supports BOSH connection. I was unable to find some links/modules for data forms(creatind and extracting dataforms) support by xmpp.js.

Can somebody help me in knowing this?

Quick response is very much appreciated.

Regards,
Guruprasad

**Comment by mwild1** [comment]
Hi,

On 22 August 2011 08:23, gurukini
reply@reply.github.com
wrote:

> Hi,
> 
> I am very much new to xmpp.js. Before i want to start working on xmpp.js I wanted to know below given two requirements.
> a) BOSH support
> b) Data Forms support

a) No (as I said in my other comment).
b) Yes and no. xmpp.js is a low-level XMPP library that allows you to
craft any XMPP stanza. This includes dataforms. However there is no
high-level API for it.

Regards,
Matthew
