### ISSUE TITLE
xmpp.js support for BOSH connection

### ISSUE THREAD

**Issue by gurukini** [mwild1/xmppjs#5]
Hi,

In xmpp.js code i noticed that it will establish a tcp(port:5347) connection. Does xmpp.js support BOSH connection also, if i want to establish a BOSH connection to my openfire xmpp server which listens at 7070(http://localhost:7070/http-bind/)?

Please let me know as early as possible. Quick response is very much appreciated.

Regards,
Guruprasad

**Comment by mwild1** [comment]
Hi Guruprasad,

On 22 August 2011 09:50, gurukini
reply@reply.github.com
wrote:

> Hi,
> 
> In xmpp.js code i noticed that it will establish a tcp(port:5347) connection. Does xmpp.js support BOSH connection also, if i want to establish a BOSH connection to my openfire xmpp server which listens at 7070(http://localhost:7070/http-bind/)?

No, xmpp.js does not support BOSH. BOSH is used for clients to connect
to the server and xmpp.js is specifically designed for server-side
code. You should look at strophe.js ( http://strophe.im/ ) for a
library with an (almost) identical API that is designed for client use
(it uses BOSH).

Regards,
Matthew
